// <copyright file="AssemblyInfo.cs" company="PublicDomain.is">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

using System.Reflection;
using System.Runtime.CompilerServices;

// Information about this assembly is defined by the following attributes. 
// Change them to the values specific to your project.

[assembly: AssemblyTitle("WeatherToText")]
[assembly: AssemblyDescription("Displays the weather in the command line (weather forecast to text).")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("PublicDomain.is")]
[assembly: AssemblyProduct("WeatherToText")]
[assembly: AssemblyCopyright("Copyright 2022 - Victor L. Senior")]
[assembly: AssemblyTrademark("publicdomain")]
[assembly: AssemblyCulture("")]

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// The form "{Major}.{Minor}.*" will automatically update the build and revision,
// and "{Major}.{Minor}.{Build}.*" will update just the revision.

[assembly: AssemblyVersion("0.6.0.*")]

// The following attributes are used to specify the signing key for the assembly, 
// if desired. See the Mono documentation for more information about signing.

//[assembly: AssemblyDelaySign(false)]
//[assembly: AssemblyKeyFile("")]
